#version: "3.8"
#services:
#  db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: rootpwd
#      MYSQL_DATABASE: tododb
#    ports:
#      - "3307:3306"
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      retries: 5

version: "3.8"

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_DATABASE: tododb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  app:
    build: .
    container_name: todo-app
    ports:
      - "8081:8080"
    environment:
      # the app container connects to the MySQL by service name "db"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tododb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always

volumes:
  db_data:
